package com.example.telproject.services;

import com.example.telproject.database.User;
import com.example.telproject.database.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Map;

@Service
public class RegisterService {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    public Boolean isPasswordStrong(String pass) { //is the password strong ?
        if(pass.length() >=4){
            return true;
        }
        return false;
    }

    public User createUser(Map<String,String> allParams) throws Exception{


        for (Map.Entry<String, String> entry : allParams.entrySet()) {
            System.out.println(entry.getKey() + "/" + entry.getValue());

            if (entry.getValue() == null || entry.getValue() == "") { //se periptwsh poy afysei kapoio keno field kata to registration
                throw new Exception("Empty Field");
            }

            if (entry.getKey() == "password" && !this.isPasswordStrong(entry.getValue())) {  //se periptwsh pou den balei strong password
                //if password not strong
                throw new Exception("Password not strong enough");

            }
        }
        System.out.println(allParams.get("password"));
        System.out.println(allParams.get("reenterpassword"));

        if(!(allParams.get("password").equals(allParams.get("reenterpassword")) )){
            throw new Exception("Different passwords given");

        }


        User new_user= new User(allParams.get("email"),allParams.get("username"),allParams.get("firstname"),allParams.get("lastname"),allParams.get("password"));
        String username= userRepository.findUserByUsername(allParams.get("username"));
        if(username !=null && !username.isEmpty() ){ //an brethei o user
             System.out.println("User  existssssssssss\n\n\n");
            throw new Exception("User with same username exists");
        }

        String email= userRepository.findUserByUsername(allParams.get("email"));
        if(email !=null && !email.isEmpty() ){ //an brethei o user
            System.out.println("User existssssssssss\n\n\n");
            throw new Exception("User with same email exists");
        }

        System.out.println("Creating userrrrrrrr\n\n\n");
        userRepository.save(new_user);


        return null;
    }
}
