package com.example.telproject;

import com.example.telproject.database.User;
import com.example.telproject.database.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;


@RestController    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class UserController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public User addNewUser (@RequestParam String name
			, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		 User n = new User();
		 n.setEmail(email);
		 n.setPassword("pass");
		 n.setRole(1);
		 n.setUsername(name);
		 n.setAdmin_boolean(1);
		 n.setCustomer_boolean(1);
		 n.setFee(1);


		 userRepository.save(n);

		return n;
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		//User user =  new User();
		return userRepository.findAll();
	}
}
